name: dagger
on:
  push:
    branches: [main]

  pull_request:
      types:
          - opened
          - reopened
          - synchronize
          - ready_for_review

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function to build and publish to ghcr.io
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call

          args: container-echo --string-arg yoyo
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
